import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import * as yaml from 'js-yaml';
import { MANAGED_PLUGINS, REQUIRED_MARKDOWN_EXTENSIONS } from './constants';

const MERMAID_FENCE_TAG = '!!python/name:pymdownx.superfences.fence_code_format';

const DEFAULT_PALETTE = [
  {
    media: '(prefers-color-scheme: light)',
    scheme: 'default',
    toggle: { icon: 'material/brightness-7', name: 'Switch to dark mode' },
  },
  {
    media: '(prefers-color-scheme: dark)',
    scheme: 'slate',
    toggle: { icon: 'material/brightness-4', name: 'Switch to light mode' },
  },
];

const MERMAID_SUPERFENCES_CONFIG = {
  'pymdownx.superfences': {
    custom_fences: [
      {
        name: 'mermaid',
        class: 'mermaid',
        format: MERMAID_FENCE_TAG,
      },
    ],
  },
};

/**
 * Preprocess YAML text to escape ALL tags that js-yaml cannot handle
 */
export const YAML_TAG_RE = /!!python\/([a-zA-Z0-9_./:-]+)/g;
export const YAML_TAG_SENTINEL = '__PYTAG__';
export const YAML_SENTINEL_RE = new RegExp(`${YAML_TAG_SENTINEL}([a-zA-Z0-9_./:-]+)`, 'g');

export function preprocessYaml(raw: string): string {
  return raw.replace(YAML_TAG_RE, `${YAML_TAG_SENTINEL}$1`);
}

export function postprocessYaml(dumped: string): string {
  return dumped.replace(YAML_SENTINEL_RE, '!!python/$1');
}

interface MkDocsConfig {
  plugins?: Array<string | Record<string, unknown>>;
  theme?: string | Record<string, unknown>;
  markdown_extensions?: Array<string | Record<string, unknown>>;
  hooks?: string[];
  [key: string]: unknown;
}

function getPluginName(plugin: string | Record<string, unknown>): string {
  if (typeof plugin === 'string') { return plugin; }
  return Object.keys(plugin)[0] ?? '';
}

function extractUserPlugins(config: MkDocsConfig): Array<string | Record<string, unknown>> {
  if (!config.plugins) { return []; }

  // We now guarantee this is a perfectly flat array of strings and single-key objects!
  return (config.plugins as Array<string | Record<string, unknown>>).filter((p) => {
    const name = getPluginName(p);
    return !['live-edit', 'live-wysiwyg', 'techdocs-core', 'glightbox'].includes(name);
  });
}

function buildPluginsBlock(
  themeName: string,
  docsDir: string,
  websocketPort: number,
  apiPort: number,
  autoGenerated: boolean,
  bindHost: string
): Array<string | Record<string, unknown>> {
  const plugins: Array<string | Record<string, unknown>> = ['search'];

  // if (themeName === 'material') {
  //   plugins.push({
  //     'techdocs-core': {
  //       use_material_search: true,
  //       use_pymdownx_blocks: true,
  //     },
  //   });
  // }

  if (autoGenerated) {
    plugins.push('mkdocs-nav-weight');
  }

  plugins.push({
    'live-edit': {
      user_docs_dir: docsDir,
      websockets_port: websocketPort,
      websockets_host: bindHost,
    },
  });

  const wysiwygConfig: Record<string, unknown> = {};
  if (apiPort > 0) {
    wysiwygConfig.api_port = apiPort;
  }
  plugins.push(
    Object.keys(wysiwygConfig).length > 0
      ? { 'live-wysiwyg': wysiwygConfig }
      : 'live-wysiwyg'
  );

  return plugins;
}

function resolveThemeName(config: MkDocsConfig, useUserTheme: boolean): string {
  if (!useUserTheme) { return 'material'; }
  const theme = config.theme;
  if (typeof theme === 'string') { return theme; }
  if (theme && typeof theme === 'object' && 'name' in theme) {
    return String(theme.name);
  }
  return 'material';
}

function applyTheme(rendered: MkDocsConfig, useUserTheme: boolean, themeName: string): void {
  if (useUserTheme) {
    // Let MkDocs natively handle the theme!
    // Just ensure it's formatted safely for the YAML dumper.
    if (typeof rendered.theme === 'string') {
      rendered.theme = { name: rendered.theme };
    }
  } else {
    rendered.theme = {
      name: 'material',
      palette: DEFAULT_PALETTE,
    };
  }
}

function addMarkdownExtensionIfMissing(config: MkDocsConfig, ext: string): void {
  if (!config.markdown_extensions) {
    config.markdown_extensions = [];
  }
  const existing = config.markdown_extensions.some((e) => {
    const name = typeof e === 'string' ? e : Object.keys(e)[0];
    return name === ext;
  });
  if (!existing) {
    config.markdown_extensions.push(ext);
  }
}

function addSuperfencesWithMermaidIfMissing(config: MkDocsConfig): void {
  if (!config.markdown_extensions) {
    config.markdown_extensions = [];
  }
  const hasSuperfences = config.markdown_extensions.some((e) => {
    const name = typeof e === 'string' ? e : Object.keys(e)[0];
    return name === 'pymdownx.superfences';
  });
  if (!hasSuperfences) {
    config.markdown_extensions.push(MERMAID_SUPERFENCES_CONFIG);
  }
}

function generateRestoreThemeHook(
  workspaceDir: string,
  themeConfig: Record<string, unknown>, // Keep this for future-proofing
  websocketPort: number,
  externalWsUrl: string
): string {
  const vscodeDir = path.join(workspaceDir, '.vscode');
  if (!fs.existsSync(vscodeDir)) {
    fs.mkdirSync(vscodeDir, { recursive: true });
  }

  const hookPath = path.join(vscodeDir, 'restore_theme.py');

  // We write the hook to ONLY handle the WebSocket redirection.
  // This allows the MkDocs 'INHERIT' logic to handle 100% of the theme/plugins.
  fs.writeFileSync(hookPath, `
def on_post_page(output, page, config, **kwargs):
    # This patch ensures the WYSIWYG editor can talk to the server
    # even through VS Code / Codespaces proxies.
    patch = """<script>
    (function() {
        const origWs = window.WebSocket;
        window.WebSocket = function(url, protocols) {
            if (url.includes(':${websocketPort}')) {
                return new origWs('${externalWsUrl}', protocols);
            }
            return new origWs(url, protocols);
        };
    })();
    </script>"""
    return output.replace('</head>', patch + '</head>')
`);

  return hookPath;
}

export interface GenerateConfigOptions {
  workspaceDir: string;
  tmpDir: string;
  websocketPort: number;
  apiPort: number;
  httpPort: number;
  bindHost: string;
  externalWsUrl: string;
  useUserTheme: boolean;
  autoGenerated: boolean;
}

// export function generateMkdocsConfig(options: GenerateConfigOptions): string {
//   const { workspaceDir, tmpDir, websocketPort, apiPort, httpPort, bindHost, externalWsUrl, useUserTheme, autoGenerated } = options;
//   const mkdocsYmlPath = path.join(workspaceDir, 'mkdocs.yml');
//   const originalContent = fs.readFileSync(mkdocsYmlPath, 'utf8');

//   fs.mkdirSync(tmpDir, { recursive: true });
//   fs.writeFileSync(path.join(tmpDir, 'original-mkdocs.yml'), originalContent);

//   const sanitized = preprocessYaml(originalContent);
//   let config: MkDocsConfig;
//   try {
//     config = yaml.load(sanitized) as MkDocsConfig ?? {};
//   } catch {
//     config = {};
//   }
// // --- NEW INHERITANCE MERGE LOGIC ---
//   if (config.INHERIT) {
//     const inheritedPath = path.resolve(workspaceDir, String(config.INHERIT));
//     if (fs.existsSync(inheritedPath)) {
//       try {
//         const inheritedContent = fs.readFileSync(inheritedPath, 'utf8');
//         const sanitizedInherited = preprocessYaml(inheritedContent);
//         const inheritedConfig = yaml.load(sanitizedInherited) as MkDocsConfig ?? {};

//         // 1. Deep merge theme (so TS knows about the features)
//         if (inheritedConfig.theme) {
//            if (!config.theme) config.theme = {};
//            if (typeof config.theme === 'object' && typeof inheritedConfig.theme === 'object') {
//               config.theme = { ...inheritedConfig.theme, ...config.theme };
//            } else {
//               config.theme = config.theme || inheritedConfig.theme;
//            }
//         }

//         // 2. Concat plugins (MkDocs child arrays overwrite parent arrays!)
//         if (inheritedConfig.plugins) {
//            const childPlugins = Array.isArray(config.plugins) ? config.plugins : [];
//            const parentPlugins = Array.isArray(inheritedConfig.plugins) ? inheritedConfig.plugins : [];
//            config.plugins = [...parentPlugins, ...childPlugins];
//         }

//         // 3. Concat markdown extensions
//         if (inheritedConfig.markdown_extensions) {
//            const childExts = Array.isArray(config.markdown_extensions) ? config.markdown_extensions : [];
//            const parentExts = Array.isArray(inheritedConfig.markdown_extensions) ? inheritedConfig.markdown_extensions : [];
//            config.markdown_extensions = [...parentExts, ...childExts];
//         }
//       } catch (err) {
//         console.error(`Warning: Failed to parse inherited config at ${inheritedPath}`, err);
//       }
//     }
//   }
//   // --- END INHERITANCE MERGE LOGIC ---

//   const themeName = resolveThemeName(config, useUserTheme);
//   const userPlugins = extractUserPlugins(config);
//   const docsDir = path.join(workspaceDir, 'docs');

//   // We no longer pass externalWsUrl into the plugin block
//   const pluginsBlock = buildPluginsBlock(themeName, docsDir, websocketPort, apiPort, autoGenerated, bindHost);

//   const rendered: MkDocsConfig = { ...config };
//   delete rendered.plugins;

//   // Bind the main server
//   rendered.dev_addr = `${bindHost}:${httpPort}`;
//   rendered.plugins = [...userPlugins, ...pluginsBlock];

//   applyTheme(rendered, useUserTheme, themeName);

//   const themeObj = (typeof rendered.theme === 'object' ? rendered.theme : {}) as Record<string, unknown>;

//   // Always generate the hook so live-reloading works for any theme
//   const hookPath = generateRestoreThemeHook(workspaceDir, themeObj, websocketPort, externalWsUrl);

//   // Append the hook to any existing hooks
//   rendered.hooks = [...(rendered.hooks ?? []), hookPath];

//   // if (themeName === 'material') {
//   //   const themeObj = rendered.theme as Record<string, unknown>;
//   //   // Pass the external URL strictly to the hook
//   //   const hookPath = generateRestoreThemeHook(workspaceDir, themeObj, websocketPort, externalWsUrl);
//   //   rendered.hooks = [...(rendered.hooks ?? []), hookPath];
//   // }

//   for (const ext of REQUIRED_MARKDOWN_EXTENSIONS) {
//     addMarkdownExtensionIfMissing(rendered, ext);
//   }
//   addSuperfencesWithMermaidIfMissing(rendered);

//   const banner = [
//     '################################################################################',
//     '# DO NOT EDIT THIS FILE while the server is running.',
//     '#',
//     '# WARNING: This entire mkdocs.yml file will be deleted. The original will be',
//     '# restored overwriting this file when the server shuts down.',
//     '#',
//     '# If you want to edit your mkdocs.yml, do so after shutting down the server.',
//     '################################################################################',
//     '',
//   ].join(os.EOL);

//   const rawYaml = yaml.dump(rendered, {
//     lineWidth: -1,
//     noRefs: true,
//     quotingType: '"',
//     forceQuotes: false,
//   });

//   const yamlContent = postprocessYaml(rawYaml);
//   const generatedContent = banner + yamlContent;

//   console.log("FINAL GENERATED CONFIG:", yamlContent);

//   fs.writeFileSync(mkdocsYmlPath, generatedContent);

//   return generatedContent;
// }

// --- NEW NORMALIZER HELPER ---
// Converts any messy mix of dictionaries and arrays into a strict MkDocs array
function normalizeMkDocsList(list: unknown): Array<string | Record<string, unknown>> {
  if (!list) return [];
  const result: Array<string | Record<string, unknown>> = [];

  // Case 1: User provided a pure dictionary (No dashes in YAML)
  if (!Array.isArray(list) && typeof list === 'object') {
    for (const [key, val] of Object.entries(list)) {
      if (val !== null && typeof val === 'object') {
        result.push({ [key]: val });
      } else {
        result.push(key);
      }
    }
    return result;
  }

  // Case 2: User provided an array (Might contain giant multi-key dictionaries)
  if (Array.isArray(list)) {
    for (const item of list) {
      if (typeof item === 'string') {
        result.push(item);
      } else if (item && typeof item === 'object') {
        // Split giant dictionaries into strict single-key MkDocs items
        for (const [key, val] of Object.entries(item)) {
          if (val !== null && typeof val === 'object') {
            result.push({ [key]: val });
          } else {
            result.push({ [key]: val ?? {} });
          }
        }
      }
    }
  }

  return result;
}

// --- NEW DEEP MERGE HELPER ---
function mergeMkDocsConfig(parent: any, child: any): any {
  const merged = { ...parent, ...child };

  // Deep merge specific dictionary keys
  const dictKeys = ['theme', 'extra'];
  for (const key of dictKeys) {
    if (parent[key] && child[key] && typeof parent[key] === 'object' && typeof child[key] === 'object') {
      merged[key] = { ...parent[key], ...child[key] };
    }
  }

  // Smart Merge for collections (Allows the user's dictionary trick!)
  const hybridKeys = ['plugins', 'markdown_extensions'];
  for (const key of hybridKeys) {
    if (parent[key] && child[key]) {
      if (!Array.isArray(parent[key]) && !Array.isArray(child[key]) && typeof parent[key] === 'object' && typeof child[key] === 'object') {
         // User cleverly used dictionaries -> Deep merge them
         merged[key] = { ...parent[key], ...child[key] };
      } else {
         // Standard MkDocs arrays -> Concatenate them
         const pArr = Array.isArray(parent[key]) ? parent[key] : [parent[key]];
         const cArr = Array.isArray(child[key]) ? child[key] : [child[key]];
         merged[key] = [...pArr, ...cArr];
      }
    } else if (parent[key] && !child[key]) {
       merged[key] = parent[key];
    }
  }

  // Pure array keys
  const arrayKeys = ['extra_css', 'extra_javascript'];
  for (const key of arrayKeys) {
    if (parent[key] || child[key]) {
      const pArr = Array.isArray(parent[key]) ? parent[key] : (parent[key] ? [parent[key]] : []);
      const cArr = Array.isArray(child[key]) ? child[key] : (child[key] ? [child[key]] : []);
      merged[key] = [...pArr, ...cArr];
    }
  }

  return merged;
}
// -----------------------------

export function generateMkdocsConfig(options: GenerateConfigOptions): string {
  const {
    workspaceDir,
    tmpDir,
    websocketPort,
    apiPort,
    httpPort,
    bindHost,
    externalWsUrl,
    useUserTheme,
    autoGenerated,
  } = options;

  const originalConfigPath = path.join(workspaceDir, 'mkdocs.yml');
  const generatedConfigPath = originalConfigPath;

  const originalContent = fs.readFileSync(originalConfigPath, 'utf8');

  // Backup original configuration to tmpDir so it can be restored later
  fs.mkdirSync(tmpDir, { recursive: true });
  fs.writeFileSync(path.join(tmpDir, 'original-mkdocs.yml'), originalContent);

  const sanitized = preprocessYaml(originalContent);
  let config = (yaml.load(sanitized) as any) || {};

  // --- FLATTEN INHERITANCE ---
  if (config.INHERIT) {
    const inheritedPath = path.resolve(path.dirname(originalConfigPath), String(config.INHERIT));
    if (fs.existsSync(inheritedPath)) {
      try {
        const parentRaw = fs.readFileSync(inheritedPath, 'utf8');
        const parentContent = preprocessYaml(parentRaw);
        const parentConfig = (yaml.load(parentContent) as any) || {};

        // Merge the parent into the child using our helper
        config = mergeMkDocsConfig(parentConfig, config);

        // CRITICAL: Delete INHERIT so the proxy file doesn't trigger pathing errors!
        delete config.INHERIT;
      } catch (err) {
        config.INHERIT_ERROR = `Failed to parse inherited file. ${err}`;
      }
    } else {
      config.INHERIT_ERROR = `Inherited file not found at path: ${inheritedPath}`;
    }
  }

  // --- APPLY NORMALIZER ---
  // Instantly fix any weird formatting from the inheritance merge (like the giant dict)
  config.plugins = normalizeMkDocsList(config.plugins);
  config.markdown_extensions = normalizeMkDocsList(config.markdown_extensions);

  // --- PREPARE PLUGINS & THEME ---
  const userPlugins = extractUserPlugins(config);
  const themeName = resolveThemeName(config, useUserTheme);
  const docsDir = path.join(workspaceDir, 'docs');

  const systemPlugins = buildPluginsBlock(
    themeName,
    docsDir,
    websocketPort,
    apiPort,
    autoGenerated,
    bindHost
  );

  // --- BUILD FINAL CONFIGURATION ---
  const rendered: MkDocsConfig = { ...config };

  // Bind the main server
  rendered.dev_addr = `${bindHost}:${httpPort}`;

  // Deduplicate plugins (Prevents the 'material/search' warning)
  const allPlugins = [...userPlugins, ...systemPlugins];
  const uniquePlugins: Array<string | Record<string, unknown>> = [];
  const seenPlugins = new Set<string>();

  for (const p of allPlugins) {
    const name = getPluginName(p);
    if (!seenPlugins.has(name)) {
      seenPlugins.add(name);
      uniquePlugins.push(p);
    }
  }
  rendered.plugins = uniquePlugins;

  applyTheme(rendered, useUserTheme, themeName);

  // Generate hook for websockets
  const themeObj = (typeof rendered.theme === 'object' ? rendered.theme : {}) as Record<string, unknown>;
  const hookPath = generateRestoreThemeHook(workspaceDir, themeObj, websocketPort, externalWsUrl);
  rendered.hooks = [...(rendered.hooks ?? []), hookPath];

  // Add required Markdown extensions for WYSIWYG
  for (const ext of REQUIRED_MARKDOWN_EXTENSIONS) {
    addMarkdownExtensionIfMissing(rendered, ext);
  }
  addSuperfencesWithMermaidIfMissing(rendered);

  // --- TRANSPARENCY / DEBUGGING HOOK ---
  const debugPath = path.join(workspaceDir, 'DEBUG_MKDOCS_PROXY.json');
  fs.writeFileSync(debugPath, JSON.stringify(rendered, null, 2));

  // CRITICAL: Clean up our custom debug keys before passing to MkDocs so it doesn't throw warnings!
  delete rendered.INHERIT_ERROR;

  const banner = [
    '################################################################################',
    '# DO NOT EDIT THIS FILE while the server is running.',
    '#',
    '# WARNING: This entire mkdocs.yml file will be deleted. The original will be',
    '# restored overwriting this file when the server shuts down.',
    '#',
    '# If you want to edit your mkdocs.yml, do so after shutting down the server.',
    '################################################################################',
    '',
  ].join(os.EOL);

  // Dump and post-process to restore !!python tags
  const rawYaml = yaml.dump(rendered, {
    lineWidth: -1,
    noRefs: true,
    quotingType: '"',
    forceQuotes: false,
  });

  const yamlContent = postprocessYaml(rawYaml);
  const generatedContent = banner + yamlContent;

  fs.writeFileSync(generatedConfigPath, generatedContent);

  return generatedConfigPath;
}

//------------------------------------------------------

export function restoreOriginalConfig(workspaceDir: string, tmpDir: string): void {
  const originalPath = path.join(tmpDir, 'original-mkdocs.yml');
  const mkdocsYmlPath = path.join(workspaceDir, 'mkdocs.yml');
  if (fs.existsSync(originalPath)) {
    fs.copyFileSync(originalPath, mkdocsYmlPath);
  }
}
